### ISSUE TITLE
Build with VS 2017 fails when the 2015 toolset is not installed

### ISSUE THREAD

**Issue by JohnWins** [avast-tl/fileformat#4]
Hi,
I have followed steps at #build-and-installation on Windows OS, and got error with cmake, and here are my operation and error log.

Steps:
1. cmake-3.10.1-win64-x64 installed with auto registered environment.
2. ActivePerl-5.24.2.2403-MSWin32-x64-403863.exe.msi with auto registered environment.
3. CMAKE_INSTALL_PREFIX=C:\Program Files\CMake\bin.
4. Developer command prompt for VS2017, cd fileformat-master dir, mkdir build and cd build...
5. cmake .. -DCMAKE_INSTALL_PREFIX="C:\Program Files\CMake\bin" -G"Visual Studio 15 2017"

Error:
`**********************************************************************
** Visual Studio 2017 Developer Command Prompt v15.0.26228.4
** Copyright (c) 2017 Microsoft Corporation
**********************************************************************
[vcvarsall.bat] Environment initialized for: 'x64'

C:\Program Files (x86)\Visual Studio 2017 Enterprise>pushd F:\user\Program\visua
l studio 2015\Projects\fileformat-master\build

F:\user\Program\visual studio 2015\Projects\fileformat-master\build>cmake .. -DC
MAKE_INSTALL_PREFIX="C:\Program Files\CMake\bin" -G"Visual Studio 15 2017"
-- Selecting Windows SDK version 10.0.14393.0 to target Windows 6.1.7601.
-- The CXX compiler identification is MSVC 19.10.25017.0
-- Check for working CXX compiler: C:/Program Files (x86)/Visual Studio 2017 Ent
erprise/VC/Tools/MSVC/14.10.25017/bin/HostX86/x86/cl.exe
-- Check for working CXX compiler: C:/Program Files (x86)/Visual Studio 2017 Ent
erprise/VC/Tools/MSVC/14.10.25017/bin/HostX86/x86/cl.exe -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Setting build type to 'Release' as none was specified.
CMake Error at deps/CMakeLists.txt:2 (add_subdirectory):
  The source directory`

So, do I have missed something ?

**Comment by s3rvac** [comment]
Hi. A couple of notes:
* I suggest using a different value for `-DCMAKE_INSTALL_PREFIX=`. Despite its name, [this variable](https://cmake.org/cmake/help/latest/variable/CMAKE_INSTALL_PREFIX.html) prescribes the path where the project should be installed, NOT the path where CMake is installed. Installing the project into CMake's directory is probably not what you want. Instead, choose a dedicated directory, e.g. `C:\projects\fileformat\install`.
* As for the CMake error, I believe that you did not pass the `--recursive` parameter when cloning the repository (see [this issue](https://github.com/avast-tl/retdec/issues/4)). Either remove the cloned repository and clone it again with
    ```
    git clone --recursive https://github.com/avast-tl/fileformat
    ```
    or, if you do not want to clone it again, simply go inside the already cloned repository and run
    ```
    git submodule update --init --recursive
    ```

Let me know if that helps.

**Comment by JohnWins** [comment]
yes, succeed in generating fileformat.sln file, but for msbuild step, still 16 error, just give that up :(
But thanks anyway.

**Comment by s3rvac** [comment]
We will gladly help you with the build, but we will need to see the error messages that MSVC emitted. Or, if you just want to use the decompiler, you can use pre-built Windows packages, which will allow you to completely skip the build process.

Anyway, feel free to reopen the issue if you would like to get the build working.

**Comment by JohnWins** [comment]
Hi, this would be very nice for your kind reply, and I have checked the source code again, then found problems with it. And I just have found that this project is not what I expected for a certain purpose. What a pity~

1. DebugInfo project
>Dir: fileformat\deps\llvm\src\lib\DebugInfo\PDB\DIA
>File: DIASession.cpp at line 60.

>   const wchar_t *msdia_dll = nullptr;
#if _MSC_VER == 1900
  msdia_dll = L"msdia140.dll"; // VS2015
#elif _MSC_VER == 1800
  msdia_dll = L"msdia120.dll"; // VS2013
#else
#error "Unknown Visual Studio version."
#endif

1). _MSC_VER=1910 for VS2017 in my case, so the error log shows "Unknown Visual Studio version."
And there is a simple patch for this:
>#if _MSC_VER == 1910
  msdia_dll = L"msdia140.dll"; // VS2017
#elif _MSC_VER == 1900
  msdia_dll = L"msdia140.dll"; // VS2015

**Comment by s3rvac** [comment]
Currently, the build does not work with VS 2017 unless the 2015 toolset is installed as well. I believe that this is what causes the build errors that you see. We have created a tracking issue for this problem: https://github.com/avast-tl/retdec/issues/55 Until the issue is fixed, the only way of compiling the library is by installing the 2015 toolset into Visual Studio.

**Comment by metthal** [comment]
@JohnWins I am not able to reproduce your problem. Today, I successfully built `fileformat` on Windows 10 with only VS2017 installed (without VS2015 toolkit). Could you please try to clean your build folder and build it again? The file you have mentioned shouldn't even be compiled, at least I wasn't able to find it in my build folder.

**Comment by s3rvac** [comment]
In [`9ab4f56e3`](https://github.com/avast-tl/llvm/commit/9ab4f56e33e9dfe3b7c1759f99d8b23baa161874), I have fixed the compilation of `DIASession.cpp` with VS 2017 when DIA SDK is installed, so the build should work now.

@JohnWins Please, can you verify that the build works now? If not, what is the next error that you got?

**Comment by JohnWins** [comment]
Hi, sorry for a delay, nowadays, pretty busy with 'homework' stuff.
@s3rvac  
I have cleaned the built folder as @metthal requests and re-download this project and compiler it again. 

1. `msbuild /m /p:Configuration=Release fileformat.sln` 
and wait... 
There is an error to "jsoncpp-project". Here is the details after command line

> fileformat/build/deps/retdec-config/deps/jsoncpp/jsoncpp-project-prefix/src/jsoncpp-project-stamp/jsoncpp-project-build-Debug.cmake:16 (message):
Command failed: 1

2. `msbuild /m /p:Configuration=Release INSTALL.vcxproj`
Same error to "jsoncpp-project"

**Comment by JohnWins** [comment]
Okay now, it tells me that the file path is too long after checking its 'jsoncpp-project-build-out.log'.
I would say, thanks, guys, and Merry Christmas :)

**Comment by s3rvac** [comment]
Thank you for the re-tried build. I believe that this is the same error as in https://github.com/avast-tl/retdec/issues/61.

In commit 565197acdb3521f46ee5d9e798f893ded5014d6f, I have reduced the length of paths created by external projects. In the case of `jsoncpp` (the offending library), the path lengths got decreased by 46 characters.

Would you be able to check the build of the current `master` branch to see whether this fixed the build for you? If not, a workaround will be to clone the repository in a shorter path (e.g. `C:\projects\fileformat`).

**Comment by JohnWins** [comment]
em, yes, it is . and it works for me in a short path,such as <C:\fileformat\build>.
Well done for this hot-fix version.

**Comment by s3rvac** [comment]
Great! I am glad that you got it working.
